### ISSUE TITLE
【DNS服务】vpc的URL在哪设置？

### ISSUE THREAD

**Issue by dnstester** [Huawei/python-openstacksdk#17]
Error
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\tests\functional\dns\v2\test_ptr.py", line 40, in setUpClass
    for _eip in ips:
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\resource2.py", line 835, in list
    params=query_params)
  File "C:\Python27\lib\site-packages\keystoneauth1\session.py", line 758, in get
    return self.request(url, 'GET', **kwargs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 67, in map_exceptions_wrapper
    return func(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 357, in request
    return super(Session, self).request(*args, **kwargs)
  File "C:\Python27\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
    args, kwargs)
  File "C:\Python27\lib\site-packages\positional\__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\keystoneauth1\session.py", line 513, in request
    **endpoint_filter)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 341, in get_endpoint
    sc_endpoint)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 217, in _get_endpoint_versions
    response = self._parse_versions_response(just_root + path)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 150, in _parse_versions_response
    response = self.get(uri)
  File "C:\Python27\lib\site-packages\keystoneauth1\session.py", line 758, in get
    return self.request(url, 'GET', **kwargs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 71, in map_exceptions_wrapper
    raise exceptions.SDKException(message=e.message, cause=e)
SDKException: Unable to establish connection to https://vpc.eu-de.otc.t-systems.com: HTTPSConnectionPool(host='vpc.eu-de.otc.t-systems.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000040F41D0>: Failed to establish a new connection: [Errno 10060] ',))

**Comment by IamFive** [comment]
一样都是设置环境变量，functional test 是在 base.py 里

**Comment by dnstester** [comment]
不知道DT上面VPC的访问的IP

**Comment by IamFive** [comment]
这个要问你们内网环境相关的同事哦，我帮不了你。

**Comment by dnstester** [comment]
我在functional/base.py中添加了VPC的endpoint,
os.environ.setdefault(
            'OS_VPC_ENDPOINT_OVERRIDE',
            'https://172.30.49.152:8443/v2/%(project_id)s'
        )
但仍然提示SDKException: Unable to establish connection to https://vpc.eu-de.otc.t-systems.com: HTTPSConnectionPool(host='vpc.eu-de.otc.t-systems.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000040F41D0>: Failed to establish a new connection: [Errno 10060] ',))

**Comment by IamFive** [comment]
你用的德电环境吗？德电环境 vpc 服务不需要设置啊

**Comment by IamFive** [comment]
你异常是连不上服务器吧

**Comment by dnstester** [comment]
我连得是德电的VPC

**Comment by IamFive** [comment]
德电环境 network 服务不需要配置 endpoint，能自动探测到。
