### ISSUE TITLE
【AS】修改弹性伸缩组--请求体错

### ISSUE THREAD

**Issue by caoyameng** [Huawei/python-openstacksdk#19]
#修改弹性伸缩组
    def test_modify_group(self):
        _group = {
          # "name": "group_name",
          # "scaling_configuration_id": "3efda1f3-22e7-42c6-aa97-15b72382586d",
          "desire_instance_number": 1,
          "min_instance_number": 1,
          "max_instance_number": 3,
          "cool_down_time": 200
        }
        to_update_group_id = "74f24256-859d-4b04-9d02-8c05bce0b2dc"
        group = self.conn.auto_scaling.update_group(to_update_group_id, **_group)
        group = self.conn.auto_scaling.get_group(group)
        # logging.info(group)
        print(group)

日志：
Error
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\tests\functional\auto_scaling\test_group_cym.py", line 78, in test_modify_group
    group = self.conn.auto_scaling.update_group(to_update_group_id, **_group)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\auto_scaling\v1\_proxy.py", line 143, in update_group
    return self._update(_group.Group, group, prepend_key=False, **attrs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\proxy2.py", line 36, in check
    return method(self, expected, actual, *args, **kwargs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\proxy2.py", line 179, in _update
    has_body=has_body)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\resource2.py", line 739, in update
    json=request.body, headers=request.headers)
  File "C:\Python27\lib\site-packages\keystoneauth1\session.py", line 774, in put
    return self.request(url, 'PUT', **kwargs)
  File "C:\Python27\Lib\site-packages\python-openstacksdk-master\openstack\session.py", line 69, in map_exceptions_wrapper
    raise exceptions.from_exception(e)
HttpException: HttpException: request body error (HTTP 400), [AS.0022] request body error

**Comment by IamFive** [comment]
代码写在 run_example 里面，那边配置了日志。

**Comment by IamFive** [comment]
安排修改了
