### ISSUE TITLE
openstack.exceptions.SDKException: public endpoint for compute service not found

### ISSUE THREAD

**Issue by luhuan01** [Huawei/python-openstacksdk#56]
![image](https://user-images.githubusercontent.com/19201057/33417765-c3703e14-d5dd-11e7-8f5d-5260a3cdfb86.png)

执行创建虚拟机操作的时候一直提示openstack.exceptions.SDKException: public endpoint for compute service not found

**Comment by IamFive** [comment]
完整的请求日志。（发送的http请求包，返回的请求包）

**Comment by luhuan01** [comment]
执行的创建虚拟机操作，具体代码是：
```
def create_vm(conn):
    os.environ.setdefault(
    'OS_COMPUTE_ENDPOINT_OVERRIDE',
    "https://ecs.apigateway-api.eu-de.hz-tsi.de/v2/%(project_id)s"
)
    server = conn.compute.create_server(name='luhuantest', flavor_id='a57c8603-12f0-4896-b024-7b9f2b26215b', image_id='ce6aba70-bf15-480f-adee-de4fa977bcd2', networks=[{"uuid": '130404c8-2e34-47bf-9b55-60d25c6a9c73'}])
    conn.compute.wait_for_server(server)

if __name__ == '__main__':
    create_vm(conn)
```

**Comment by luhuan01** [comment]
同样的请求地址另一台机器执行的时候没有任何报错

**Comment by luhuan01** [comment]
这个是请求的内容：
```
url = /servers
method = POST
json = {'server': {'flavorRef': 'a57c8603-12f0-4896-b024-7b9f2b26215b', 'networks': [{'uuid': '130404c8-2e34-47bf-9b55-60d25c6a9c73'}], 'imageRef': 'ce6aba70-bf15-480f-adee-de4fa977bcd2', 'name': 'luhuantest'}}
original_ip = None
user_agent = None
redirect = None
authenticated = True
endpoint_filter = {'region_name': None, 'service_name': None, 'interface': 'public', 'version': None, 'service_type': 'compute', 'requires_project_id': False, 'api_version': None}
auth = None
requests_auth = None
raise_exc = True
allow_reauth = True
log = True
endpoint_override = None
connect_retries = 0
logger = <logging.Logger object at 0x7f2e10a96d50>
allow = None
client_name = None
client_version = None
microversion = None
microversion_service_type = None
kwargs = {'headers': {'X-Auth-Token'：...}}
```

**Comment by IamFive** [comment]
你在你的代码前面加上，然后把请求那块的日志贴上来。

```
import logging
import os

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT)
root_log = logging.getLogger()
root_log.setLevel(logging.DEBUG)
requests_log = logging.getLogger('requests.packages.urllib3')
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True
```

**Comment by luhuan01** [comment]
```
2017-11-30 15:11:15,303 REQ: curl -g -i --insecure -X GET https://10.175.48.125:31943/v3 -H "Accept: application/json" -H "User-Agent: openstacksdk/0.9.17 keystoneauth1/3.2.0 python-requests/2.12.0 CPython/2.7.13"
2017-11-30 15:11:15,308 Starting new HTTPS connection (1): 10.175.48.125
/usr/local/python2.7.13/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-11-30 15:11:15,342 https://10.175.48.125:31943 "GET /v3 HTTP/1.1" 200 None
2017-11-30 15:11:15,350 RESP: [200] Server: product only Date: Thu, 30 Nov 2017 07:09:00 GMT Content-Type: application/json Transfer-Encoding: chunked Connection: keep-alive X-IAM-Trace-Id: RouteID-er-18-1506992683-535588947 Content-Encoding: gzip 
RESP BODY: {"version":{"media-types":[{"type":"application/vnd.openstack.identity-v3+json","base":"application/json"}],"links":[{"rel":"self","href":"https://iam.cn-north-1.myhwclouds.com/v3/"}],"id":"v3.6","updated":"2016-04-04T00:00:00Z","status":"stable"}}

2017-11-30 15:11:15,350 Making authentication request to https://10.175.48.125:31943/v3/auth/tokens
/usr/local/python2.7.13/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-11-30 15:11:15,388 https://10.175.48.125:31943 "POST /v3/auth/tokens HTTP/1.1" 201 None
2017-11-30 15:11:15,391 {"token": {"methods": ["password"], "roles": [{"name": "te_admin", "id": "1992c1df9ad6412e9c833032cd70ca8f"}, {"name": "op_gated_scc_nids", "id": "0"}, {"name": "op_gated_molap", "id": "0"}, {"name": "op_gated_scc_waf", "id": "0"}, {"name": "op_gated_ais_ocr_vat_invoice", "id": "0"}, {"name": "op_gated_op_gated_scc_hvd", "id": "0"}, {"name": "op_gated_GACS", "id": "0"}, {"name": "op_gated_ces_agt", "id": "0"}, {"name": "op_gated_cold", "id": "0"}, {"name": "op_gated_rds_myopt", "id": "0"}, {"name": "op_gated_op_gated_scc_scs", "id": "0"}, {"name": "op_gated_ddm", "id": "0"}, {"name": "op_gated_scc_pts", "id": "0"}, {"name": "op_gated_scc_ars", "id": "0"}, {"name": "op_gated_ecs_normalexclusive", "id": "0"}, {"name": "op_gated_scc_sas", "id": "0"}, {"name": "op_gated_cloudcc", "id": "0"}, {"name": "op_gated_rds_hwsql", "id": "0"}, {"name": "op_gated_csbs", "id": "0"}, {"name": "op_gated_waf", "id": "0"}, {"name": "op_gated_obs_warm_cold", "id": "0"}, {"name": "op_gated_kvm", "id": "0"}, {"name": "op_gated_scc_wtp", "id": "0"}, {"name": "op_gated_lld", "id": "0"}, {"name": "op_gated_IM", "id": "0"}, {"name": "op_gated_ecs_recyclebin", "id": "0"}, {"name": "op_gated_LTS", "id": "0"}, {"name": "op_gated_cad", "id": "0"}, {"name": "op_gated_cloudide", "id": "0"}, {"name": "op_gated_ais_dispatch_planning", "id": "0"}, {"name": "op_gated_hss", "id": "0"}, {"name": "op_gated_fgs", "id": "0"}, {"name": "op_gated_dcs", "id": "0"}, {"name": "op_gated_oms", "id": "0"}, {"name": "op_gated_functionstage", "id": "0"}, {"name": "op_gated_dws_feature", "id": "0"}, {"name": "op_gated_dess", "id": "0"}, {"name": "op_legacy", "id": "0"}, {"name": "op_gated_drds", "id": "0"}, {"name": "op_gated_ais_pickup_planning", "id": "0"}, {"name": "op_gated_cloudIM", "id": "0"}, {"name": "op_gated_ais_ocr_id_card", "id": "0"}, {"name": "op_gated_scc_hvd", "id": "0"}, {"name": "op_gated_op_gated_rds_customercloud", "id": "0"}, {"name": "op_gated_ecs_normal_s3", "id": "0"}, {"name": "op_gated_mobiletest", "id": "0"}, {"name": "op_gated_gpu", "id": "0"}, {"name": "op_gated_testgc001", "id": "0"}, {"name": "op_gated_obs_cold", "id": "0"}, {"name": "op_gated_gated_kms", "id": "0"}, {"name": "op_gated_ais_image_recapture_detect", "id": "0"}, {"name": "op_gated_ecs_hpc", "id": "0"}, {"name": "op_gated_scc_scs", "id": "0"}, {"name": "op_gated_op_gated_scc_waf", "id": "0"}, {"name": "op_gated_mls", "id": "0"}, {"name": "op_gated_FunctionGraph", "id": "0"}, {"name": "op_gated_tag", "id": "0"}, {"name": "op_gated_tms", "id": "0"}, {"name": "op_gated_cc", "id": "0"}, {"name": "op_gated_dcs_cluster", "id": "0"}, {"name": "op_gated_warm", "id": "0"}, {"name": "op_gated_ecs_hmem", "id": "0"}, {"name": "op_gated_scc_ssa", "id": "0"}, {"name": "op_gated_ais_image_antiporn", "id": "0"}, {"name": "op_gated_webscan", "id": "0"}, {"name": "op_gated_ais_ocr_custom_form", "id": "0"}, {"name": "op_gated_op_gated_scc_pts", "id": "0"}, {"name": "op_gated_elasticsearch", "id": "0"}, {"name": "op_gated_ecs_diskintensive", "id": "0"}, {"name": "op_gated_ais_image_tagging", "id": "0"}, {"name": "op_gated_rds_customercloud", "id": "0"}, {"name": "op_gated_apig", "id": "0"}, {"name": "op_gated_dcs_memcached", "id": "0"}, {"name": "op_gated_rds-transfer", "id": "0"}, {"name": "op_gated_op_gated_test12", "id": "0"}], "expires_at": "2017-12-01T07:09:00.393000Z", "project": {"domain": {"name": "cwx290878", "id": "81150746f0434889b87f116989a65be1"}, "name": "eastchina", "id": "69dd2706789f4ef18d8f7f49e5f035f6"}, "catalog": [{"endpoints": [{"interface": "public", "url": "https://dns.cn-north-1.myhwclouds.com", "region": "*", "region_id": "*", "id": "c80c16b1073f4836bd860f46f667a6f3"}], "type": "dns", "name": "", "id": "2ecc66b59f1b45e8999dd453aacdb76a"}, {"endpoints": [{"interface": "public", "url": "https://iam.cn-north-1.myhwclouds.com/v3", "region": "*", "region_id": "*", "id": "d2983f677ce14f1e81cbb6a9345a107a"}], "type": "identity", "name": "keystone", "id": "fd631b3426cb40f0919091d5861d8fea"}], "user": {"domain": {"name": "cwx290878", "id": "81150746f0434889b87f116989a65be1"}, "name": "cwx290878", "id": "349ab2230418451db997bd77dae05904"}, "issued_at": "2017-11-30T07:09:00.393000Z"}}
Traceback (most recent call last):
  File "test_ecs.py", line 30, in <module>
    create_vm(conn)
  File "test_ecs.py", line 26, in create_vm
    server = conn.compute.create_server(name='luhuantest', flavor_id='a57c8603-12f0-4896-b024-7b9f2b26215b', image_id='ce6aba70-bf15-480f-adee-de4fa977bcd2', networks=[{"uuid": '130404c8-2e34-47bf-9b55-60d25c6a9c73'}]) 
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/compute/v2/_proxy.py", line 325, in create_server
    return self._create(_server.Server, **attrs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/proxy2.py", line 194, in _create
    return res.create(self._session)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/resource2.py", line 588, in create
    json=request.body, headers=request.headers)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/keystoneauth1/session.py", line 849, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/session.py", line 68, in map_exceptions_wrapper
    raise exceptions.SDKException(message=e.message, cause=e)
openstack.exceptions.SDKException: public endpoint for compute service not found
```

**Comment by luhuan01** [comment]
你好，请问有什么其他方式能联系到您么？或者共享下桌面麻烦您帮我看下

**Comment by IamFive** [comment]
没办法哦，我不是华为内网的。

**Comment by IamFive** [comment]
看了日志，你的代码是用户github上的这个吗？

**Comment by luhuan01** [comment]
哦哦好哒，谢谢~刚刚贴的日志结果能找到原因么

**Comment by luhuan01** [comment]
是github上下载的

**Comment by luhuan01** [comment]
pip install openstacksdk==0.9.16

**Comment by IamFive** [comment]
但是运行时候加载的代码跟github上不一致。

  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/resource2.py", line 588, in create

resource2.py 的 588 行 不是create 方法。

**Comment by IamFive** [comment]
> pip install openstacksdk==0.9.16

这个安装的不是开发库的代码，是公共仓库的代码。

**Comment by luhuan01** [comment]
```
563     def create(self, session, prepend_key=True):
564         """Create a remote resource based on this instance.
565 
566         :param session: The session to use for making this request.
567         :type session: :class:`~openstack.session.Session`
568         :param prepend_key: A boolean indicating whether the resource_key
569                             should be prepended in a resource creation
570                             request. Default to True.
571 
572         :return: This :class:`Resource` instance.
573         :raises: :exc:`~openstack.exceptions.MethodNotSupported` if
574                  :data:`Resource.allow_create` is not set to ``True``.
575         """
576         if not self.allow_create:
577             raise exceptions.MethodNotSupported(self, "create")
578 
579         if self.put_create:
580             request = self._prepare_request(requires_id=True,
581                                             prepend_key=prepend_key)
582             response = session.put(request.uri, endpoint_filter=self.service,
583                                    json=request.body, headers=request.headers)
584         else:
585             request = self._prepare_request(requires_id=False,
586                                             prepend_key=prepend_key)
587             response = session.post(request.uri, endpoint_filter=self.service,
588                                     json=request.body, headers=request.headers)
589 
590         self._translate_response(response)
591         return self
592 

```

**Comment by IamFive** [comment]
你搜下 resource2.py 自己看下就知道了。

**Comment by luhuan01** [comment]
```
[root@falcon-server huawei-python-openstacksdk]# python setup.py install
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.1s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.1s)
running build
running build_py
running egg_info
writing requirements to openstacksdk.egg-info/requires.txt
writing openstacksdk.egg-info/PKG-INFO
writing top-level names to openstacksdk.egg-info/top_level.txt
writing dependency_links to openstacksdk.egg-info/dependency_links.txt
writing pbr to openstacksdk.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'openstacksdk.egg-info/SOURCES.txt'
running install_lib
running install_egg_info
removing '/usr/local/python2.7.13/lib/python2.7/site-packages/openstacksdk-0.9.17.dev177-py2.7.egg-info' (and everything under it)
Copying openstacksdk.egg-info to /usr/local/python2.7.13/lib/python2.7/site-packages/openstacksdk-0.9.17.dev177-py2.7.egg-info
```
这个就是github上下载然后安装的还是同样的错误

**Comment by IamFive** [comment]
`/usr/local/python2.7.13/lib/python2.7/site-packages/` 下面看看有没有安装成功，是不是github上的代码。

**Comment by luhuan01** [comment]
报错信息：
```
Traceback (most recent call last):
  File "test_ecs.py", line 30, in <module>
    create_vm(conn)
  File "test_ecs.py", line 26, in create_vm
    server = conn.compute.create_server(name='luhuantest', flavor_id='a57c8603-12f0-4896-b024-7b9f2b26215b', image_id='ce6aba70-bf15-480f-adee-de4fa977bcd2', networks=[{"uuid": '130404c8-2e34-47bf-9b55-60d25c6a9c73'}]) 
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/compute/v2/_proxy.py", line 325, in create_server
    return self._create(_server.Server, **attrs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/proxy2.py", line 194, in _create
    return res.create(self._session)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/resource2.py", line 588, in create
    json=request.body, headers=request.headers)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/keystoneauth1/session.py", line 849, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/session.py", line 68, in map_exceptions_wrapper
    raise exceptions.SDKException(message=e.message, cause=e)
openstack.exceptions.SDKException: public endpoint for compute service not found
```

**Comment by IamFive** [comment]
不太清楚。你把那个文件删除了，重新安装试试看。

pip install git+https://github.com/Huawei/python-openstacksdk.git

**Comment by luhuan01** [comment]
嗯呢我试试，这个openstack文件夹是下载openstackclient的时候装的么，这个时间还是昨天的

**Comment by IamFive** [comment]
是的。

**Comment by luhuan01** [comment]
内网限制下不下来，只能在桌面下载zip文件在上传

**Comment by IamFive** [comment]
一样的，找张栋要一份安装包，重新安装就可以了应该。

**Comment by luhuan01** [comment]
python setup.py install安装的时候报错：
```
[root@falcon-server python-openstacksdk-master]# python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/pbr/packaging.py", line 750, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name openstacksdk was given, but was not able to be found.
error in setup command: Error parsing /home/sdk/python-openstacksdk-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name openstacksdk was given, but was not able to be found.
```

**Comment by IamFive** [comment]
找张栋要安装包，源码是不行的，源码里面没有版本信息。

**Comment by luhuan01** [comment]
你好，我用张栋给的安装包，现在还是这个错：
```
[root@falcon-server 411sdk]# python test_ecs.py 
2017-11-30 16:06:44,028 REQ: curl -g -i --insecure -X GET https://10.175.48.125:31943/v3 -H "Accept: application/json" -H "User-Agent: openstacksdk/0.9.17 keystoneauth1/3.2.0 python-requests/2.18.4 CPython/2.7.13"
2017-11-30 16:06:44,030 Starting new HTTPS connection (1): 10.175.48.125
/usr/local/python2.7.13/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-11-30 16:06:44,078 https://10.175.48.125:31943 "GET /v3 HTTP/1.1" 200 None
2017-11-30 16:06:44,079 RESP: [200] Server: product only Date: Thu, 30 Nov 2017 08:04:29 GMT Content-Type: application/json Transfer-Encoding: chunked Connection: keep-alive X-IAM-Trace-Id: RouteID-er-18-1506992683-535887061 Content-Encoding: gzip 
RESP BODY: {"version":{"media-types":[{"type":"application/vnd.openstack.identity-v3+json","base":"application/json"}],"links":[{"rel":"self","href":"https://iam.cn-north-1.myhwclouds.com/v3/"}],"id":"v3.6","updated":"2016-04-04T00:00:00Z","status":"stable"}}

2017-11-30 16:06:44,079 Making authentication request to https://10.175.48.125:31943/v3/auth/tokens
/usr/local/python2.7.13/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-11-30 16:06:44,130 https://10.175.48.125:31943 "POST /v3/auth/tokens HTTP/1.1" 201 None
2017-11-30 16:06:44,131 {"token": {"methods": ["password"], "roles": [{"name": "te_admin", "id": "1992c1df9ad6412e9c833032cd70ca8f"}, {"name": "op_gated_scc_nids", "id": "0"}, {"name": "op_gated_molap", "id": "0"}, {"name": "op_gated_scc_waf", "id": "0"}, {"name": "op_gated_ais_ocr_vat_invoice", "id": "0"}, {"name": "op_gated_op_gated_scc_hvd", "id": "0"}, {"name": "op_gated_GACS", "id": "0"}, {"name": "op_gated_ces_agt", "id": "0"}, {"name": "op_gated_cold", "id": "0"}, {"name": "op_gated_rds_myopt", "id": "0"}, {"name": "op_gated_op_gated_scc_scs", "id": "0"}, {"name": "op_gated_ddm", "id": "0"}, {"name": "op_gated_scc_pts", "id": "0"}, {"name": "op_gated_scc_ars", "id": "0"}, {"name": "op_gated_ecs_normalexclusive", "id": "0"}, {"name": "op_gated_scc_sas", "id": "0"}, {"name": "op_gated_cloudcc", "id": "0"}, {"name": "op_gated_rds_hwsql", "id": "0"}, {"name": "op_gated_csbs", "id": "0"}, {"name": "op_gated_waf", "id": "0"}, {"name": "op_gated_obs_warm_cold", "id": "0"}, {"name": "op_gated_kvm", "id": "0"}, {"name": "op_gated_scc_wtp", "id": "0"}, {"name": "op_gated_lld", "id": "0"}, {"name": "op_gated_IM", "id": "0"}, {"name": "op_gated_ecs_recyclebin", "id": "0"}, {"name": "op_gated_LTS", "id": "0"}, {"name": "op_gated_cad", "id": "0"}, {"name": "op_gated_cloudide", "id": "0"}, {"name": "op_gated_ais_dispatch_planning", "id": "0"}, {"name": "op_gated_hss", "id": "0"}, {"name": "op_gated_fgs", "id": "0"}, {"name": "op_gated_dcs", "id": "0"}, {"name": "op_gated_oms", "id": "0"}, {"name": "op_gated_functionstage", "id": "0"}, {"name": "op_gated_dws_feature", "id": "0"}, {"name": "op_gated_dess", "id": "0"}, {"name": "op_legacy", "id": "0"}, {"name": "op_gated_drds", "id": "0"}, {"name": "op_gated_ais_pickup_planning", "id": "0"}, {"name": "op_gated_cloudIM", "id": "0"}, {"name": "op_gated_ais_ocr_id_card", "id": "0"}, {"name": "op_gated_scc_hvd", "id": "0"}, {"name": "op_gated_op_gated_rds_customercloud", "id": "0"}, {"name": "op_gated_ecs_normal_s3", "id": "0"}, {"name": "op_gated_mobiletest", "id": "0"}, {"name": "op_gated_gpu", "id": "0"}, {"name": "op_gated_testgc001", "id": "0"}, {"name": "op_gated_obs_cold", "id": "0"}, {"name": "op_gated_gated_kms", "id": "0"}, {"name": "op_gated_ais_image_recapture_detect", "id": "0"}, {"name": "op_gated_ecs_hpc", "id": "0"}, {"name": "op_gated_scc_scs", "id": "0"}, {"name": "op_gated_op_gated_scc_waf", "id": "0"}, {"name": "op_gated_mls", "id": "0"}, {"name": "op_gated_FunctionGraph", "id": "0"}, {"name": "op_gated_tag", "id": "0"}, {"name": "op_gated_tms", "id": "0"}, {"name": "op_gated_cc", "id": "0"}, {"name": "op_gated_dcs_cluster", "id": "0"}, {"name": "op_gated_warm", "id": "0"}, {"name": "op_gated_ecs_hmem", "id": "0"}, {"name": "op_gated_scc_ssa", "id": "0"}, {"name": "op_gated_ais_image_antiporn", "id": "0"}, {"name": "op_gated_webscan", "id": "0"}, {"name": "op_gated_ais_ocr_custom_form", "id": "0"}, {"name": "op_gated_op_gated_scc_pts", "id": "0"}, {"name": "op_gated_elasticsearch", "id": "0"}, {"name": "op_gated_ecs_diskintensive", "id": "0"}, {"name": "op_gated_ais_image_tagging", "id": "0"}, {"name": "op_gated_rds_customercloud", "id": "0"}, {"name": "op_gated_apig", "id": "0"}, {"name": "op_gated_dcs_memcached", "id": "0"}, {"name": "op_gated_rds-transfer", "id": "0"}, {"name": "op_gated_op_gated_test12", "id": "0"}], "expires_at": "2017-12-01T08:04:29.113000Z", "project": {"domain": {"name": "cwx290878", "id": "81150746f0434889b87f116989a65be1"}, "name": "eastchina", "id": "69dd2706789f4ef18d8f7f49e5f035f6"}, "catalog": [{"endpoints": [{"interface": "public", "url": "https://dns.cn-north-1.myhwclouds.com", "region": "*", "region_id": "*", "id": "c80c16b1073f4836bd860f46f667a6f3"}], "type": "dns", "name": "", "id": "2ecc66b59f1b45e8999dd453aacdb76a"}, {"endpoints": [{"interface": "public", "url": "https://iam.cn-north-1.myhwclouds.com/v3", "region": "*", "region_id": "*", "id": "d2983f677ce14f1e81cbb6a9345a107a"}], "type": "identity", "name": "keystone", "id": "fd631b3426cb40f0919091d5861d8fea"}], "user": {"domain": {"name": "cwx290878", "id": "81150746f0434889b87f116989a65be1"}, "name": "cwx290878", "id": "349ab2230418451db997bd77dae05904"}, "issued_at": "2017-11-30T08:04:29.113000Z"}}
Traceback (most recent call last):
  File "test_ecs.py", line 30, in <module>
    create_vm(conn)
  File "test_ecs.py", line 26, in create_vm
    server = conn.compute.create_server(name='luhuantest', flavor_id='a57c8603-12f0-4896-b024-7b9f2b26215b', image_id='ce6aba70-bf15-480f-adee-de4fa977bcd2', networks=[{"uuid": '130404c8-2e34-47bf-9b55-60d25c6a9c73'}]) 
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/compute/v2/_proxy.py", line 325, in create_server
    return self._create(_server.Server, **attrs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/proxy2.py", line 194, in _create
    return res.create(self._session)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/resource2.py", line 588, in create
    json=request.body, headers=request.headers)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/keystoneauth1/session.py", line 849, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/python2.7.13/lib/python2.7/site-packages/openstack/session.py", line 68, in map_exceptions_wrapper
    raise exceptions.SDKException(message=e.message, cause=e)
openstack.exceptions.SDKException: public endpoint for compute service not found
```

**Comment by luhuan01** [comment]
你好，除了github怎么还能联系您呢

**Comment by IamFive** [comment]
我也搞不懂你这代码不是github上的

**Comment by luhuan01** [comment]
openstackclient是用pip install安装的，我也不清楚哪里出了问题了，你之前有遇到过这类问题么？可能原因在哪块呢

**Comment by IamFive** [comment]
正常不太可能的，你把openstack文件夹删除了，然后重新 `python setup.py install` 。
